[project]
name = "lit_helper"
version = "0.1.0"
description = "lit_helper using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "black>=25.1.0",
    "chromadb>=0.5.23",
    "crewai[tools]>=0.152.0,<1.0.0",
    "llama-index>=0.13.2",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
    "rank-bm25>=0.2.2",
    "ruff>=0.12.9",
]

[project.scripts]
lit_helper = "lit_helper.main:run"
run_crew = "lit_helper.main:run"
train = "lit_helper.main:train"
replay = "lit_helper.main:replay"
test = "lit_helper.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
